ALTER TABLE "AiRun"
ADD COLUMN "queuedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN "startedAt" TIMESTAMP(3),
ADD COLUMN "openAiStartedAt" TIMESTAMP(3),
ADD COLUMN "openAiFinishedAt" TIMESTAMP(3),
ADD COLUMN "durationMs" INTEGER,
ADD COLUMN "openAiDurationMs" INTEGER,
ADD COLUMN "cachedInputTokens" INTEGER;
